// Code generated by MockGen. DO NOT EDIT.
// Source: internal/client/service/secret/service.go

// Package mocks is a generated GoMock package.
package secret_service

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	cobra "github.com/spf13/cobra"
)

// MockServiceInterface is a mock of ServiceInterface interface.
type MockServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockServiceInterfaceMockRecorder
}

// MockServiceInterfaceMockRecorder is the mock recorder for MockServiceInterface.
type MockServiceInterfaceMockRecorder struct {
	mock *MockServiceInterface
}

// NewMockServiceInterface creates a new mock instance.
func NewMockServiceInterface(ctrl *gomock.Controller) *MockServiceInterface {
	mock := &MockServiceInterface{ctrl: ctrl}
	mock.recorder = &MockServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceInterface) EXPECT() *MockServiceInterfaceMockRecorder {
	return m.recorder
}

// CreateBankCard mocks base method.
func (m *MockServiceInterface) CreateBankCard(cmd *cobra.Command, args []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateBankCard", cmd, args)
}

// CreateBankCard indicates an expected call of CreateBankCard.
func (mr *MockServiceInterfaceMockRecorder) CreateBankCard(cmd, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBankCard", reflect.TypeOf((*MockServiceInterface)(nil).CreateBankCard), cmd, args)
}

// CreateBinary mocks base method.
func (m *MockServiceInterface) CreateBinary(cmd *cobra.Command, args []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateBinary", cmd, args)
}

// CreateBinary indicates an expected call of CreateBinary.
func (mr *MockServiceInterfaceMockRecorder) CreateBinary(cmd, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBinary", reflect.TypeOf((*MockServiceInterface)(nil).CreateBinary), cmd, args)
}

// CreateLoginPass mocks base method.
func (m *MockServiceInterface) CreateLoginPass(cmd *cobra.Command, args []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateLoginPass", cmd, args)
}

// CreateLoginPass indicates an expected call of CreateLoginPass.
func (mr *MockServiceInterfaceMockRecorder) CreateLoginPass(cmd, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLoginPass", reflect.TypeOf((*MockServiceInterface)(nil).CreateLoginPass), cmd, args)
}

// CreateText mocks base method.
func (m *MockServiceInterface) CreateText(cmd *cobra.Command, args []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateText", cmd, args)
}

// CreateText indicates an expected call of CreateText.
func (mr *MockServiceInterfaceMockRecorder) CreateText(cmd, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateText", reflect.TypeOf((*MockServiceInterface)(nil).CreateText), cmd, args)
}

// Delete mocks base method.
func (m *MockServiceInterface) Delete(cmd *cobra.Command, args []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Delete", cmd, args)
}

// Delete indicates an expected call of Delete.
func (mr *MockServiceInterfaceMockRecorder) Delete(cmd, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockServiceInterface)(nil).Delete), cmd, args)
}

// Get mocks base method.
func (m *MockServiceInterface) Get(cmd *cobra.Command, args []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Get", cmd, args)
}

// Get indicates an expected call of Get.
func (mr *MockServiceInterfaceMockRecorder) Get(cmd, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockServiceInterface)(nil).Get), cmd, args)
}

// Update mocks base method.
func (m *MockServiceInterface) Update(cmd *cobra.Command, args []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Update", cmd, args)
}

// Update indicates an expected call of Update.
func (mr *MockServiceInterfaceMockRecorder) Update(cmd, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockServiceInterface)(nil).Update), cmd, args)
}
