// Code generated by MockGen. DO NOT EDIT.
// Source: internal/client/repository/secret/client.go

// Package mocks is a generated GoMock package.
package secret_client

import (
	context "context"
	reflect "reflect"

	secret "github.com/VladimirSh98/GophKeeper/internal/client/repository/secret"
	proto "github.com/VladimirSh98/GophKeeper/proto"
	gomock "github.com/golang/mock/gomock"
)

// MockClientInterface is a mock of ClientInterface interface.
type MockClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClientInterfaceMockRecorder
}

// MockClientInterfaceMockRecorder is the mock recorder for MockClientInterface.
type MockClientInterfaceMockRecorder struct {
	mock *MockClientInterface
}

// NewMockClientInterface creates a new mock instance.
func NewMockClientInterface(ctrl *gomock.Controller) *MockClientInterface {
	mock := &MockClientInterface{ctrl: ctrl}
	mock.recorder = &MockClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientInterface) EXPECT() *MockClientInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockClientInterface) Create(ctx context.Context, token string, dataType secret.DataType, content []byte, metadata map[string]string) (*proto.SecretModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, token, dataType, content, metadata)
	ret0, _ := ret[0].(*proto.SecretModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockClientInterfaceMockRecorder) Create(ctx, token, dataType, content, metadata interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockClientInterface)(nil).Create), ctx, token, dataType, content, metadata)
}

// Delete mocks base method.
func (m *MockClientInterface) Delete(ctx context.Context, token string, secretID int) (*proto.SecretModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, token, secretID)
	ret0, _ := ret[0].(*proto.SecretModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockClientInterfaceMockRecorder) Delete(ctx, token, secretID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockClientInterface)(nil).Delete), ctx, token, secretID)
}

// Get mocks base method.
func (m *MockClientInterface) Get(ctx context.Context, token string) (*proto.GetSecretsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, token)
	ret0, _ := ret[0].(*proto.GetSecretsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockClientInterfaceMockRecorder) Get(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockClientInterface)(nil).Get), ctx, token)
}

// GetByID mocks base method.
func (m *MockClientInterface) GetByID(ctx context.Context, token string, secretID int) (*proto.SecretModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, token, secretID)
	ret0, _ := ret[0].(*proto.SecretModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockClientInterfaceMockRecorder) GetByID(ctx, token, secretID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockClientInterface)(nil).GetByID), ctx, token, secretID)
}

// Update mocks base method.
func (m *MockClientInterface) Update(ctx context.Context, token string, secretID int, content []byte, metadata map[string]string) (*proto.SecretModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, token, secretID, content, metadata)
	ret0, _ := ret[0].(*proto.SecretModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockClientInterfaceMockRecorder) Update(ctx, token, secretID, content, metadata interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockClientInterface)(nil).Update), ctx, token, secretID, content, metadata)
}
