syntax = "proto3";

import "google/protobuf/timestamp.proto";

package proto;

option go_package = "github.com/VladimirSh98/GophKeeper/proto";


message SecretModel {
  int64 id = 1;
  int64 user_id = 2;
  bool archived = 3;
  google.protobuf.Timestamp created_at = 4;
  google.protobuf.Timestamp updated_at = 5;
  DataType data_type = 6;
  bytes content = 7;
  map<string, string> metadata = 8;
}

enum DataType {
  LOGIN_PASSWORD = 0;
  TEXT_DATA = 1;
  BINARY_DATA = 2;
  BANK_CARD = 3;
}

message CreateSecretRequest {
  DataType data_type = 1;
  bytes content = 2;
  map<string, string> metadata = 3;
}

message EditSecretRequest {
  bool archived = 1;
  bytes content = 2;
  map<string, string> metadata = 3;
}

message DeleteSecretRequest {
  int64 id = 1;
}

message GetSecretsRequest {
}

message GetSecretsResponse {
  repeated SecretModel secrets = 1;
}

service Secret {
  rpc Create (CreateSecretRequest) returns (SecretModel);
  rpc Edit (EditSecretRequest) returns (SecretModel);
  rpc Delete (DeleteSecretRequest) returns (SecretModel);
  rpc Get (GetSecretsRequest) returns (GetSecretsResponse);
}