// Code generated by MockGen. DO NOT EDIT.
// Source: internal/server/repository/secret/repository.go

// Package mocks is a generated GoMock package.
package secret

import (
	context "context"
	reflect "reflect"

	secret "github.com/VladimirSh98/GophKeeper/internal/server/repository/secret"
	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, userID, dataType int, content, metadata []byte) (secret.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID, dataType, content, metadata)
	ret0, _ := ret[0].(secret.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, userID, dataType, content, metadata interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, userID, dataType, content, metadata)
}

// DeleteByID mocks base method.
func (m *MockRepository) DeleteByID(ctx context.Context, login string, secretID int) (secret.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, login, secretID)
	ret0, _ := ret[0].(secret.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockRepositoryMockRecorder) DeleteByID(ctx, login, secretID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockRepository)(nil).DeleteByID), ctx, login, secretID)
}

// DeleteByLogin mocks base method.
func (m *MockRepository) DeleteByLogin(ctx context.Context, login string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByLogin", ctx, login)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByLogin indicates an expected call of DeleteByLogin.
func (mr *MockRepositoryMockRecorder) DeleteByLogin(ctx, login interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByLogin", reflect.TypeOf((*MockRepository)(nil).DeleteByLogin), ctx, login)
}

// GetSecretByIDUser mocks base method.
func (m *MockRepository) GetSecretByIDUser(ctx context.Context, secretID int, login string) (secret.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretByIDUser", ctx, secretID, login)
	ret0, _ := ret[0].(secret.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecretByIDUser indicates an expected call of GetSecretByIDUser.
func (mr *MockRepositoryMockRecorder) GetSecretByIDUser(ctx, secretID, login interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretByIDUser", reflect.TypeOf((*MockRepository)(nil).GetSecretByIDUser), ctx, secretID, login)
}

// GetSecretsByUser mocks base method.
func (m *MockRepository) GetSecretsByUser(ctx context.Context, login string) ([]secret.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretsByUser", ctx, login)
	ret0, _ := ret[0].([]secret.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecretsByUser indicates an expected call of GetSecretsByUser.
func (mr *MockRepositoryMockRecorder) GetSecretsByUser(ctx, login interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretsByUser", reflect.TypeOf((*MockRepository)(nil).GetSecretsByUser), ctx, login)
}

// UpdateByID mocks base method.
func (m *MockRepository) UpdateByID(ctx context.Context, login string, secretID int, content, metadata []byte) (secret.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", ctx, login, secretID, content, metadata)
	ret0, _ := ret[0].(secret.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MockRepositoryMockRecorder) UpdateByID(ctx, login, secretID, content, metadata interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockRepository)(nil).UpdateByID), ctx, login, secretID, content, metadata)
}
