// Code generated by MockGen. DO NOT EDIT.
// Source: internal/client/service/user/service.go

// Package mocks is a generated GoMock package.
package user_service

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	cobra "github.com/spf13/cobra"
)

// MockServiceInterface is a mock of ServiceInterface interface.
type MockServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockServiceInterfaceMockRecorder
}

// MockServiceInterfaceMockRecorder is the mock recorder for MockServiceInterface.
type MockServiceInterfaceMockRecorder struct {
	mock *MockServiceInterface
}

// NewMockServiceInterface creates a new mock instance.
func NewMockServiceInterface(ctrl *gomock.Controller) *MockServiceInterface {
	mock := &MockServiceInterface{ctrl: ctrl}
	mock.recorder = &MockServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceInterface) EXPECT() *MockServiceInterfaceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockServiceInterface) Delete(cmd *cobra.Command, args []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Delete", cmd, args)
}

// Delete indicates an expected call of Delete.
func (mr *MockServiceInterfaceMockRecorder) Delete(cmd, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockServiceInterface)(nil).Delete), cmd, args)
}

// Login mocks base method.
func (m *MockServiceInterface) Login(cmd *cobra.Command, args []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Login", cmd, args)
}

// Login indicates an expected call of Login.
func (mr *MockServiceInterfaceMockRecorder) Login(cmd, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockServiceInterface)(nil).Login), cmd, args)
}

// Register mocks base method.
func (m *MockServiceInterface) Register(cmd *cobra.Command, args []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Register", cmd, args)
}

// Register indicates an expected call of Register.
func (mr *MockServiceInterfaceMockRecorder) Register(cmd, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockServiceInterface)(nil).Register), cmd, args)
}
